# DO NOT RENAME defaultMessage!
# This is the message that will be used if the player has no other join/leave messages available to them
defaultMessage:
  messages:
    join:
      - "&f[&a+&f] &f%player_name%"
    leave:
      - "&f[&c-&f] &f%player_name%"

customMessages:
# The example join/leave message requires players to have the "welcome.example" permission
# You can set permissions to whatever you want! ex. "wow.a.cool.permission" or "group.mod"
# It does not have any placeholder requirements
# You can list multiple join/leave messages in each section!
# If a player has multiple join/leave messages that are applicable to them the plugin will choose at random
  example:
    messages:
      join:
        - "&f[&a+&f] &eHello, &b%player_name%&e! Welcome to the server."
        - "&f[&a+&f] &eHello, &b%player_name%&e! Say hi everyone!"
      leave:
        - "&f[&c-&f] &eGoodbye, &b%player_name%&e! Cya later!"
        - "&f[&c-&f] &eBye, &b%player_name%&e!"
    permission: welcome.example
    placeholders: []

# Just like the example message except this one has hex color codes!
  hexColorExample:
    messages:
      join:
        - "&f[&a+&f] &eHello, &b%player_name%&e! This is a &#43FBA8hex color message."
      leave:
        - "&f[&c-&f] &eGoodbye, &b%player_name%&e! This is a &#43FBA8hex color message."
    permission: welcome.hexcolorexample
    placeholders: []

# You can also use placeholders for welcome message conditions
# permissible operators for checking placeholders are:
# '==', '>=', '<=', '>', and '<' for placeholders that return numbers
# 'matches' and 'contains' for placeholders that return strings
#
#
#
# The exampleBoth option requires the player to have the "welcome.exampleboth" permission.
# It also requires the player's health to be 20, You can use any PAPI placeholders for placeholder conditions
  exampleBoth:
    messages:
      join:
        - "&f[&a+&f] &eHello, &b%player_name%&e! BOTH."
      leave:
        - "&f[&c-&f] &eGoodbye, &b%player_name%&e! BOTH."
    permission: welcome.exampleboth
    placeholders:
      - "%player_health% == 20"

# The examplePlaceholder option does not require a permission and only requires the placeholders to be true.
# If you don't want to permission you can simply remove the "permission:" option or set it to an empty string with ""
  examplePlaceholder:
    messages:
      join:
        - "&f[&a+&f] &eHello, &b%player_name%&e! You have more than 2 health and less than 18 and your name is KermX!"
      leave:
        - "&f[&c-&f] &eBye, &b%player_name%&e!"
    permission: ""
    placeholders:
      - "%player_health% > 2"
      - "%player_health% < 18"
      - "%player_name% matches KermX"