name: PrismaWelcome
version: '${project.version}'
main: me.kermx.prismawelcome.PrismaWelcome
api-version: '1.20'
depend:
  - PlaceholderAPI
commands:
  prismawelcome:
    description: Reloads PrismaWelcome configuration
    usage: /prismawelcome reload
    permission: prismawelcome.reload